---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_name: chef
  product_version: 14.1.12
  install_strategy: always

verifier:
  name: inspec

# Every bento box supported by Chef 14
platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: ubuntu-16.04-i386
  - name: ubuntu-14.04
  - name: ubuntu-14.04-i386
  - name: ubuntu-12.04
  - name: ubuntu-12.04-i386
  - name: debian-9.4
  - name: debian-9.4-i386
  - name: debian-8.10
  - name: debian-8.10-i386
  - name: debian-7.11
  - name: debian-7.11-i386
  - name: centos-7.5
  - name: centos-6.9
  - name: centos-6.9-i386
  - name: centos-5.11
  - name: centos-5.11-i386
  - name: oracle-7.5
  - name: oracle-6.9
  - name: oracle-6.9-i386
  - name: oracle-5.11
  - name: oracle-5.11-i386
  - name: fedora-28
  - name: fedora-27
  - name: fedora-26
  - name: stakahashi/amazonlinux2
  - name: realreadme/amazon2016.09
  - name: opensuse-leap-42.3
  - name: freebsd-11.1
  - name: freebsd-11.1-i386
  - name: freebsd-10.4
  - name: freebsd-10.4-i386
  - name: mwrock/Windows2016
    transport:
      name: winrm
  - name: devopsgroup-io/windows_server-2012r2-standard-amd64-nocm
  - name: salesforce/server2008r2
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[win_dns::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      win_dns:
        interface_alias: 'ethernet'
        nameservers: ['137.229.15.5', '137.229.15.9', '8.8.8.8']
        suffix: 'alaska.edu'
        register: true
    includes:
      - mwrock/Windows2016
      - devopsgroup-io/windows_server-2012r2-standard-amd64-nocm
      - salesforce/server2008r2
